server:
  port: 8080
  servlet: 
    context-path: /ee-spring-boot-2.2.2-ztree-3.5

#DataSourcespring:
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/spring_boot_ztree?userSSL=true&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT
    username: root
    password: robot_123456#
  devtools:
    restart:
      trigger-file: trigger.txt
  main:
    banner-mode: "off"
mybatis-plus:
  global-config:
    banner: false # 是否显示mybatis-plus的图标