#DataSourcespring:
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://
    username: 
    password: 
  devtools:
    restart:
      trigger-file: trigger.txt
  main:
    banner-mode: "off"
mybatis-plus:
  global-config:
    banner: false # 是否显示mybatis-plus的图标