server:
  port: 9000
spring:
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:mysql://192.168.3.9:3306/study?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&AllowPublicKeyRetrieval=True
    username: root
    password: robot_123456#
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true