server:
  port: 9001

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/spring_security?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: robot_123456#

mybatis:
  type-aliases-package: com.ppnt.spring.security.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com: debug

# 下面几个是自定义的，rsa也是自定义的
rsa:
  key:
    pubKeyPath: D:\code\java\java-study\java-ee-spring-boot-study\maven\java-ee-spring-boot-2.1.3-study\authentication-server\id_key_rsa.pub
    priKeyPath: D:\code\java\java-study\java-ee-spring-boot-study\maven\java-ee-spring-boot-2.1.3-study\authentication-server\id_key_rsa
    