#DataSourcespring:
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/study_mybatis_plus?userSSL=true&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT
    username: root
    password: 
  devtools:
    restart:
      trigger-file: trigger.txt
  main:
    banner-mode: "off"
mybatis-plus:
  global-config:
    banner: false # 是否显示mybatis-plus的图标